import { type Meta, type StoryObj } from '@storybook/nextjs';

import { TreeSelect } from '../../../libs/ui';
import { ThemeDecorator } from '../../ThemeDecorator';

const meta: Meta<typeof TreeSelect> = {
  title: 'Form/TreeSelect',
  decorators: [ThemeDecorator],
  parameters: {
    layout: 'fullScreen',
  },
  component: TreeSelect,
  argTypes: {},
  tags: ['autodocs'],
};

export default meta;

type Story = StoryObj<typeof TreeSelect>;

export const Default: Story = {
  args: {
    label: 'Discipline',
    isRequired: true,
    defaultValues: ['1', '1-1', '1-2', '2-1', '3-1', '3-3'],
    sections: ['Respiratory', 'Therapies', 'Chiropractic'],
    bifurcate: true,
    onChange: (e) => {
      console.log(e);
    },
    options: [
      {
        id: '1',
        label: 'Physical Therapy',
        value: 'physical_therapy',
        isChecked: false,
        isPartialChecked: false,
        isExpanded: false,
        isParent: true,
        section: 'Therapies',
        children: [
          {
            id: '1-1',
            label: 'Orthopedic Physical Therapy',
            value: 'ortho_physical_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '1',
            isChild: true,
            section: 'Therapies',
            children: [],
          },
          {
            id: '1-2',
            label: 'Neurological Physical Therapy',
            value: 'neuro_physical_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '1',
            section: 'Therapies',
            isChild: true,
            children: [],
          },
        ],
      },
      {
        id: '2',
        label: 'Occupational Therapy',
        value: 'occupational_therapy',
        isChecked: false,
        isPartialChecked: false,
        isExpanded: false,
        isParent: true,
        section: 'Therapies',
        children: [
          {
            id: '2-1',
            label: 'Pediatric Occupational Therapy',
            value: 'pediatric_ot',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '2',
            isChild: true,
            section: 'Therapies',
            children: [],
          },
        ],
      },
      {
        id: '3',
        label: 'Speech and Language Pathology',
        value: 'speech_language_pathology',
        isChecked: false,
        isPartialChecked: false,
        isExpanded: false,
        isParent: true,
        section: 'Therapies',
        children: [
          {
            id: '3-1',
            label: 'Speech Therapy',
            value: 'speech_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '3',
            isChild: true,
            section: 'Therapies',
            children: [],
          },
          {
            id: '3-2',
            label: 'Language Intervention',
            value: 'language_intervention',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '3',
            section: 'Therapies',
            isChild: true,
            children: [],
          },
          {
            id: '3-3',
            label: 'Fluency Disorders',
            value: 'fluency_disorders',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '3',
            isChild: true,
            section: 'Therapies',
            children: [],
          },
        ],
      },
      {
        id: '4',
        label: 'Respiratory Therapy',
        value: 'respiratory_therapy',
        isChecked: false,
        isPartialChecked: false,
        isExpanded: false,
        isParent: true,
        section: 'Respiratory',
        children: [],
      },
      {
        id: '5',
        label: 'Recreational Therapy',
        value: 'recreational_therapy',
        isChecked: false,
        isPartialChecked: false,
        isExpanded: false,
        isParent: true,
        section: 'Respiratory',
        children: [
          {
            id: '5-1',
            label: 'Adventure Therapy',
            value: 'adventure_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '5',
            section: 'Respiratory',
            isChild: true,
            children: [],
          },
          {
            id: '5-2',
            label: 'Expressive Arts Therapy',
            value: 'expressive_arts_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '5',
            section: 'Respiratory',
            isChild: true,
            children: [],
          },
        ],
      },
      {
        id: '6',
        label: 'Music Therapy',
        value: 'music_therapy',
        isChecked: false,
        isPartialChecked: false,
        isExpanded: false,
        isParent: true,
        section: 'Respiratory',
        children: [
          {
            id: '6-1',
            label: 'Neurologic Music Therapy',
            value: 'neuro_music_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '6',
            section: 'Respiratory',
            isChild: true,
            children: [],
          },
        ],
      },
      {
        id: '7',
        label: 'Art Therapy',
        value: 'art_therapy',
        isChecked: false,
        isPartialChecked: false,
        isExpanded: false,
        section: 'Respiratory',
        isParent: true,
        children: [
          {
            id: '7-1',
            label: 'Mandala Therapy',
            value: 'mandala_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '7',
            section: 'Respiratory',
            isChild: true,
            children: [],
          },
          {
            id: '7-2',
            label: 'Color Therapy',
            value: 'color_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '7',
            section: 'Respiratory',
            isChild: true,
            children: [],
          },
          {
            id: '7-3',
            label: 'Sculpting Therapy',
            value: 'sculpting_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '7',
            section: 'Respiratory',
            isChild: true,
            children: [],
          },
          {
            id: '7-4',
            label: 'Painting Therapy',
            value: 'painting_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '7',
            section: 'Respiratory',
            isChild: true,
            children: [],
          },
        ],
      },
      {
        id: '8',
        label: 'Chiropractic Care',
        value: 'chiropractic_care',
        isChecked: false,
        isPartialChecked: false,
        isExpanded: false,
        isParent: true,
        section: 'Chiropractic',
        children: [
          {
            id: '8-1',
            label: 'Spinal Manipulation',
            value: 'spinal_manipulation',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '8',
            section: 'Chiropractic',
            isChild: true,
            children: [],
          },
          {
            id: '8-2',
            label: 'Soft Tissue Therapy',
            value: 'soft_tissue_therapy',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '8',
            section: 'Chiropractic',
            isChild: true,
            children: [],
          },
          {
            id: '8-3',
            label: 'Activator Technique',
            value: 'activator_technique',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '8',
            section: 'Chiropractic',
            isChild: true,
            children: [],
          },
          {
            id: '8-4',
            label: 'Flexion-Distraction',
            value: 'flexion_distraction',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '8',
            section: 'Chiropractic',
            isChild: true,
            children: [],
          },
          {
            id: '8-5',
            label: 'Therapeutic Exercise',
            value: 'therapeutic_exercise',
            isChecked: false,
            isPartialChecked: false,
            isExpanded: false,
            parentId: '8',
            isChild: true,
            section: 'Chiropractic',
            children: [],
          },
        ],
      },
    ],
  },
};
