trigger:
  branches:
    include:
      - dev
      - main
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  scriptsPath: '.azure-pipelines/scripts'

stages:
  - stage: Build
    displayName: 'Build Library'
    jobs:
      - template: templates/build-library.yml
